### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by andrewlangston** [nkossally/Poll_Anywhere#3]
Hey Najja,

Good work on the initial DB schema. This will prove immensely helpful to you during the actual building process. A few comments to be addressed:

- [x] In the `polls` table, what purpose to `next_id` and `previous_id` serve? What does this data represent? Please leave a comment here with details.
- [x] Does PollEverywhere require that `polls` belong to a group? I believe not, in which case a poll's `group_id` should allow null values (to represent the fact that they do not belong to a group).
- [x] The `responses` table looks to be a duplicate of `choices`. I understand that both are necessary, but shouldn't `responses` not have a body?

Let me know if you have any questions.

**Comment by nkossally** [comment]
1) In answer to your first question, I am undecided about whether to have next_id and previous_id columns. Users can reorder polls in a group just by clicking polls and and dragging them around. I attached screenshots showing a re-orderings of the "what is the best borough" and "do you like cats or dogs" polls that are under the group "First Group." In addition, when you take polls that are all in one group, you can click next and previous, as with nodes. And the first poll is the "next" poll of the last poll, and the the last poll is the "previous" poll of the first poll. I am not sure I will work quickly enough to add the functionality of users clicking and dragging, but I would love to do that. Is this easy?
2) Polls have a specified group, or are put in the "Ungrouped" group by default.
3) Choices are the the possible responses respondents can make to multiple choice polls. Responses are the actual responses. So, there may be five choices for a poll: a, b, c, and d. But there may be a hundred responses if a hundred people answer the poll.
<img width="847" alt="screen shot 2019-01-24 at 8 13 41 am" src="https://user-images.githubusercontent.com/35144945/51680863-f2d10300-1fb0-11e9-887c-db4efb26c85a.png">
<img width="848" alt="screen shot 2019-01-24 at 8 13 25 am" src="https://user-images.githubusercontent.com/35144945/51680870-f6fd2080-1fb0-11e9-8ab0-c4e6c75814e6.png">

**Comment by andrewlangston** [comment]
Thanks for your responses! My own for your reference:

1. Much appreciated re: this breakdown. Let's leave the `next_id` and `previous_id` columns, as those will prove useful for the drag-and-drop functionality. It will require some clever CSS styling, but is certainly doable.
2. Since polls can be "ungrouped", you should allow null in the `group_id` column of your `polls` table.
3. Since `responses` are effectively just joins of `choices` to `users`, please edit the `responses` table to reflect this. A response will not have a `body` or `poll_id`, just a `choice_id` and `user_id`. Please don't hesitate to let me know if you have questions about this one in particular!

**Comment by nkossally** [comment]
1) Okay. I will keep the previous and next id, and set previous and next to be a poll's own id if it is ungrouped. But I was actually beginning to think that I may not need a previous and next column if a group is simply an array, and it would be easy to figure out what previous and next are without columns. Let me know what you think.
2) Gotcha.
3) I will have two types of polls: multiple choice and free response. So, for that reason, I think that sometimes the body of a response will just be the body of a choice (for multiple choice polls), and other times it will not. Am I off the mark here?

**Comment by nkossally** [comment]
Actually, I will just allow previous and next to be null when a poll is ungrouped.

**Comment by andrewlangston** [comment]
Najja,

Since we will not be keeping polls in an array in our database, we won't have any way to ensure they stay in the correct order. I would advise keeping the `previous_id` and `next_id` columns.

As for responses: you are quite on the mark! Thanks for clarifying. I will close this issue, so please continue to work on the actual build out of `polls` functionality, and let me know if you have any questions!
